[package]
name = "blosc-src"
version = "0.2.2"
authors = ["Magnus Ulimoen <magnus@ulimoen.dev>"]
edition = "2021"
build = "build.rs"
links = "blosc"
license-file = "c-blosc/LICENSE.txt"
exclude = [
    "c-blosc/compat/**",
    "c-blosc/tests/**",
    "c-blosc/bench/**",
    "c-blosc/internal-complibs/zlib-1.2.13/**",
    "c-blosc/internal-complibs/zstd-1.5.5/legacy/**",
]
repository = "https://github.com/mulimoen/rust-blosc-src"
keywords = ["compression"]
categories = ["external-ffi-bindings", "compression"]
description = "FFI bindings for blosc-c"

[features]
lz4 = []
zstd = []
zlib = ["dep:libz-sys"]

[build-dependencies]
cc = "1.0"

[dependencies]
libz-sys = { version = "1.1.12", optional = true, default-features = false, features = ["static", "libc"] }
