[package]
name = "blosc-src"
version = "0.1.1"
authors = ["Magnus Ulimoen <magnus@ulimoen.dev>"]
edition = "2021"
build = "build.rs"
links = "blosc"
license-file = "c-blosc/LICENSES/BLOSC.txt"
exclude = [
    "c-blosc/compat/**",
    "c-blosc/tests/**",
    "c-blosc/bench/**",
]
repository = "https://github.com/mulimoen/rust-blosc-src"
keywords = ["compression"]
categories = ["external-ffi-bindings", "compression"]
description = "FFI bindings for blosc-c"

[features]
lz4 = []
zstd = []
zlib = []

[build-dependencies]
cc = "1.0"
